Fix sigalarm for windows
bakdata/kpops pull request #213
Opened 2023-05-09 08:18 UTC by irux

2023-05-09 09:35 UTC, raminqaf requested changes

2023-05-09 09:35 UTC, raminqaf commented on kpops/component_handlers/kafka_connect/timeout.py
> +    # signal.signal(signal.SIGALRM, handler)
Remove old commented code please

2023-05-09 09:35 UTC, raminqaf commented on kpops/component_handlers/kafka_connect/timeout.py
> +        coro = asyncio.to_thread(func)
Can you give this variable a more meaningful name please?

2023-05-09 09:37 UTC, raminqaf requested changes

2023-05-17 09:14 UTC, irux commented
Yes! for example now all the connector test that depends on the timeout function works https://github.com/bakdata/kpops/blob/fix/windows/tests/component_handlers/kafka_connect/test_connect_wrapper.py#L122

2023-05-17 09:23 UTC, sujuka99 approved these changes
LGTM!

Please wait for another approval, too.

2023-05-17 09:29 UTC, philipp94831 approved these changes

2023-05-22 08:08 UTC, disrupted requested changes

2023-05-22 12:16 UTC, irux commented on kpops/component_handlers/kafka_connect/timeout.py
> +    async def main_supervisor(func, secs):
@disrupted done!

2023-05-22 13:55 UTC, merged