Add windows support
bakdata/kpops pull request #217
Opened 2023-05-17 07:28 UTC by irux

2023-05-31 11:11 UTC, disrupted commented
please reference the associated issues

2023-05-31 11:15 UTC, disrupted requested changes

2023-05-31 11:15 UTC, disrupted commented on kpops/utils/environment.py
> +
delete empty line

2023-05-31 11:15 UTC, disrupted commented on kpops/utils/environment.py
> +    def __get_transformation(self) -> Callable[[str], str]:
this looks like a staticmethod

2023-05-31 13:39 UTC, raminqaf submitted a review, later dismissed
LGTM!

2023-05-31 14:23 UTC, sujuka99 submitted a review, later dismissed
LGTM

2023-05-31 14:27 UTC, disrupted submitted a review, later dismissed

2023-06-02 12:51 UTC, sujuka99 approved these changes

2023-06-02 12:51 UTC, merged