add --namespace option to Helm template command
bakdata/kpops pull request #237
Opened 2023-06-08 14:21 UTC by raminqaf

2023-06-08 14:26 UTC, disrupted commented on kpops/component_handlers/helm_wrapper/helm.py
> +        :param str namespace: The namespace the command should execute in
```suggestion
        :param str namespace: The Kubernetes namespace the command should execute in
```

2023-06-08 15:10 UTC, sujuka99 requested changes
Looks good! Suggested improvements to the docstring.

2023-06-08 15:10 UTC, sujuka99 commented on kpops/component_handlers/helm_wrapper/helm.py
> +        :param str namespace: The namespace the command should execute in
```suggestion
        :param namespace: The namespace the command should execute in
        :type namespace: str
```

2023-06-08 15:10 UTC, sujuka99 commented on kpops/component_handlers/helm_wrapper/helm.py
>          :param str chart: Helm chart to be templated
```suggestion
        :param release_name: the release name for which the command is ran
        :type release_name: str
        :param chart: Helm chart to be templated
        :type chart: str
```

2023-06-08 15:10 UTC, sujuka99 commented on kpops/component_handlers/helm_wrapper/helm.py
>          :type flags: HelmTemplateFlags
```suggestion
        :param flags: the flags to be set for `helm template`, defaults to HelmTemplateFlags()
        :type flags: HelmTemplateFlags, optional
```

2023-06-09 07:42 UTC, sujuka99 approved these changes

2023-06-09 09:59 UTC, merged