Update Poetry version in CI
bakdata/kpops pull request #247
Opened 2023-06-13 16:22 UTC by sujuka99

2023-06-13 16:43 UTC, disrupted commented on .github/actions/update-docs/action.yml
>      - name: Install python and set up Poetry
please capitalize Python

2023-06-13 17:01 UTC, sujuka99 commented on .github/actions/update-docs/action.yml
>      - name: Install python and set up Poetry
done

2023-06-14 07:04 UTC, disrupted requested changes

2023-06-14 07:04 UTC, disrupted commented on .github/workflows/ci.yaml
>        - name: Install python and set up Poetry
here as well

2023-06-14 07:12 UTC, sujuka99 commented on .github/workflows/ci.yaml
>        - name: Install python and set up Poetry
done

2023-06-14 08:22 UTC, disrupted approved these changes

2023-06-14 10:33 UTC, merged