Update release and publish workflows
bakdata/kpops pull request #254
Opened 2023-06-19 08:26 UTC by irux

Closes #85

2023-06-19 08:32 UTC, irux commented
@raminqaf @disrupted how would you label this PR in order to appear in the changelog ? should I add all `area` labels to the changelog config ?

2023-06-19 09:50 UTC, disrupted commented
> @raminqaf @disrupted how would you label this PR in order to appear in the changelog ? should I add all `area` labels to the changelog config ?

looks good to me as it is

2023-06-19 09:55 UTC, disrupted commented on .github/workflows/release.yaml
> +      release-type: ${{inputs.release-type}}
surrounding space for consistency
```suggestion
      release-type: ${{ inputs.release-type }}
```

2023-06-19 09:57 UTC, disrupted commented
tags will from now on be created without the leading `v`, right?

2023-06-19 10:19 UTC, irux commented
> tags will from now on be created without the leading `v`, right?

yes! that's how we build the action :)

2023-06-19 10:20 UTC, irux commented
> > @raminqaf @disrupted how would you label this PR in order to appear in the changelog ? should I add all `area` labels to the changelog config ?
> 
> looks good to me as it is

so, how should we label this PR ?

2023-06-19 10:23 UTC, disrupted commented
> 

`area/CI` is good, it doesn't even have to be part of the changelog. it's not relevant to kpops users

2023-06-19 11:49 UTC, sujuka99 commented
closes #85 ?

2023-06-19 11:56 UTC, sujuka99 approved these changes
LGTM

2023-06-19 12:20 UTC, raminqaf commented on .github/workflows/release.yaml
> +    uses: bakdata/ci-templates/.github/workflows/python-poetry-release.yaml@v1.22.0
```suggestion
    name: Publish to PyPI
    uses: bakdata/ci-templates/.github/workflows/python-poetry-release.yaml@v1.22.0
```

2023-06-20 09:54 UTC, disrupted requested changes

2023-06-20 09:54 UTC, disrupted commented on .github/workflows/ci.yaml
> +    name: Publish Snapshot to TestPyPI
```suggestion
    name: Publish snapshot to TestPyPI
```

2023-06-20 09:54 UTC, disrupted commented on .github/workflows/release.yaml
> +    name: build project and create GitHub release
this doesn't "build the project"
```suggestion
    name: Release
```

2023-06-20 09:54 UTC, disrupted commented on .github/workflows/release.yaml
>    update-docs:
`needs` must be updated

2023-06-20 09:54 UTC, disrupted commented on .github/workflows/release.yaml
update workflow name

2023-06-20 09:56 UTC, disrupted requested changes

2023-06-20 12:09 UTC, disrupted approved these changes

2023-06-20 12:52 UTC, merged