Add malva to dprint
bakdata/kpops pull request #385
Opened 2023-11-03 22:22 UTC by sujuka99

closes #382

2023-11-06 07:41 UTC, disrupted requested changes
please also run the new formatter

2023-11-06 07:41 UTC, disrupted commented on dprint.json
>      "**/*.{md}"
`css` (and possibly other) file extensions needs to be added here

2023-11-22 13:24 UTC, raminqaf commented on dprint.json
> +    "**/*.{sass}"
are these necessary?

2023-11-22 13:24 UTC, raminqaf commented on docs/docs/stylesheets/extra.css
just double check the docs on the dev if everything is fine after this refactoring

2023-11-22 13:39 UTC, raminqaf commented on dprint.json
> +    "**/*.{sass}"
Then remove them please

2023-11-22 13:41 UTC, sujuka99 commented on dprint.json
> +    "**/*.{sass}"
removed

2023-11-22 13:49 UTC, sujuka99 commented on docs/docs/stylesheets/extra.css
Looks good to me, I didn't check extensively, but from what I saw there aren't obvious problems

2023-11-22 13:52 UTC, merged