[WIP]: Separate KPOps API from the CLI
bakdata/kpops pull request #489
Opened 2024-05-21 12:57 UTC by raminqaf

2024-05-21 15:20 UTC, disrupted requested changes
nice! 🤩

2024-05-21 15:20 UTC, disrupted commented on kpops/pipeline.py
> +    @computed_field(title="Step Names")
imo doesn't make sense to include this on model dump

2024-05-21 15:20 UTC, disrupted commented on kpops/pipeline.py
> +    def create(
why not put this in api module? imo it doesn't belong to the Pipeline class

2024-05-21 15:20 UTC, disrupted commented on kpops/pipeline.py
> +    def setup_handlers(config: KpopsConfig) -> ComponentHandlers:
since those are component handlers I wouldn't add it here

2024-05-22 09:26 UTC, disrupted commented on kpops/api/registry.py
how about `kpops.registry`?

2024-05-22 09:27 UTC, disrupted commented on kpops/api/api.py
how about `kpops/api/__init__.py` to avoid the double api?

2024-05-22 09:30 UTC, disrupted commented on kpops/api/custom_formatter.py
how about `logs` or `logging`? we could move some more stuff to it (see other comment)

2024-05-22 09:30 UTC, disrupted commented on kpops/api/api.py
> +    log.info("\n")
we could move this to the logs module

2024-05-22 09:31 UTC, disrupted commented on kpops/cli/main.py
>  import dtyper
now that we have a proper `api` module we can remove the dependency on `dtyper`

2024-05-22 11:21 UTC, raminqaf commented on kpops/api/api.py
after moving it into the __init__ file I get a -.-
```
E   ImportError: cannot import name 'KafkaConnectorConfig' from partially initialized module 'kpops.component_handlers.kafka_connect.model' (most likely due to a circular import) (/Users/ramingharib/Developer/bakdata/kpops/kpops/component_handlers/kafka_connect/model.py)

```

2024-05-22 11:32 UTC, disrupted commented on kpops/api/api.py
that's weird. for me all the tests are passing after renaming it

2024-05-22 11:36 UTC, raminqaf commented on kpops/api/registry.py
Even moving this cuases 
```
E   ImportError: cannot import name 'KafkaConnectorConfig' from partially initialized module 'kpops.component_handlers.kafka_connect.model' (most likely due to a circular import) (/Users/ramingharib/Developer/bakdata/kpops/kpops/component_handlers/kafka_connect/model.py)
```

2024-05-22 11:53 UTC, disrupted commented on kpops/api/registry.py
alright, then let's leave it as-is

2024-05-22 12:03 UTC, disrupted requested changes

2024-05-22 12:03 UTC, disrupted commented on kpops/cli/main.py
>  @app.command(  # pyright: ignore[reportCallIssue] https://github.com/rec/dtyper/issues/8
those dtyper-specific Pyright pragmas can be removed now

2024-05-22 12:08 UTC, disrupted requested changes

2024-05-22 12:08 UTC, disrupted commented on kpops/api/__init__.py
> +    steps: str | None = None,
for the Python API function signature I would prefer directly using `set[str] | None`, `parse_steps` should be moved to the CLI

2024-05-22 12:25 UTC, raminqaf commented on tests/cli/test_handlers.py
They can but I was not 100% this is a good idea. we have named them `test_generate` or `test_manifest` and have a mix of both inside and they are located in the `tests/pipeline`. I moved the `test_registry` to `tests/api` though

2024-05-22 13:59 UTC, disrupted commented on tests/cli/test_handlers.py
all good, I mostly meant this and the other ones in `tests/cli`

2024-05-22 16:00 UTC, disrupted approved these changes
LGTM, great effort! 🙌🏻

2024-05-23 05:18 UTC, merged