Change topic_name variable to output_topic_name
bakdata/kpops pull request #50
Opened 2022-12-28 14:30 UTC by MichaelKora

Fixes #28

2022-12-28 15:20 UTC, raminqaf reviewed
Could you please add a test to the `test_pipeline.py` that uses these variables in the `pipeline.yaml`?

2023-01-02 08:25 UTC, disrupted requested changes

2023-01-02 08:25 UTC, disrupted commented on tests/pipeline/test_pipeline.py
> +    def with_customed_config(self, tmpdir, snapshot):
either `custom_config` or `customized_config`

2023-01-02 11:24 UTC, disrupted requested changes

2023-01-02 11:24 UTC, disrupted commented on tests/pipeline/test_pipeline.py
> +        enriched_pipeline = load_yaml_file(Path(output_file_path))
please add
```suggestion
        enriched_pipeline = load_yaml_file(Path(output_file_path))
        assert isinstance(enriched_pipeline, dict)
```
for the type checker

2023-01-02 11:34 UTC, disrupted requested changes

2023-01-02 11:34 UTC, disrupted commented on tests/pipeline/test_pipeline.py
> +        snapshot.assert_match(enriched_pipeline, "test-pipeline")
please add the new snapshot to this PR

2023-01-02 13:04 UTC, merged